version: '2'

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.http
    container_name: traefik
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    restart: always
    networks:
      - web
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    cap_drop:
      - all
    cap_add:
      - net_bind_service

networks:
  web:
    external: true