# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

    # http should be redirected to https
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    # https is the default
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik-example.co"
watch = true
exposedbydefault = false

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "letsencrypt@traefik-example.co"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true